name: CI tests

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  merge_group:
  workflow_call:

jobs:
  format:
    name: Code Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
      - uses: oven-sh/setup-bun@v2
      - uses: biomejs/setup-biome@v2
      - run: just format

  lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
      - uses: biomejs/setup-biome@v2
      - run: just lint

  check:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
      - uses: oven-sh/setup-bun@v2
      - uses: biomejs/setup-biome@v2
      - run: just check

  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
      - uses: oven-sh/setup-bun@v2
      - uses: biomejs/setup-biome@v2
      - id: font-version
        run: just font-version >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: .cache/fonts
          key: cache-font-${{ steps.font-version.outputs.font-version }}
      - uses: actions/cache@v4
        with:
          path: .cache/og-images
          key: cache-og-${{ steps.font-version.outputs.font-version }}-${{ hashFiles('src/utils/og-templates/*.*') }}-${{ hashFiles('content/**/*.*') }}
          restore-keys: |
            cache-og-${{ steps.font-version.outputs.font-version }}-${{ hashFiles('src/utils/og-templates/*.*') }}-
      - run: just build
